name: godot-ci
description: Docker image to export Godot Engine games. Templates for Gitlab CI/GitHub Actions deploy to GitLab/GitHub Pages or Itch.io
author: aBarichello
branding:
  color: gray-dark
  icon: git-merge
runs: 
  using: 'docker'
  image: 'docker://barichello/godot-ci:latest@sha256:cdcca31e9194fd59a68a63f4b1b9c3981716819c520cd6f7966c5d72ca7246bd'
